In [9]:
#Assignment 2
a, b, c = map(int, input("Enter three numbers").split())
if a >= b and a >= c:
    print(f"largest of the three integers is {a}")
elif b >= a and b >= c:
    print(f"largest of the three integers is {b}")
elif c >= a and c >= b:
    print(f"largest of the three integers is {c}")


    
    
    

Enter three numbers 1 2 3


largest of the three integers is 3


In [10]:
#Assignment 3
def triangle_checker(a, b, c):
    if a + b > c and b + c > a and a + c > b:
        if b*b == (a*a) + (c*c) or (a*a) == (b*b) + (c*c) or (c*c) == (a*a) + (b*b):
            print("The following sides represents a Right angled triangle")
        else:
            print("The following sides represent a triangle")
    else:
        print("The following sides does not represent a triangle")
n1, n2, n3 = map(int, input("Enter three numbers").split())
triangle_checker(n1, n2, n3)

Enter three numbers 1 2 3


The following sides does not represent a triangle


In [16]:
#Assignment 4
import numpy as np 
mat1 = [[1,2,3],[4,5,6],[7,8,9]]
mat1 = np.array(mat1)
mat2 = np.eye(3)
result = mat1 + mat2
print(result)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [22]:
#Assignment 5
pan_no = input("Enter your PAN number")
valid = True
if len(pan_no) != 10:
    valid = False
else:
    for i in range (0,5):
        if pan_no[i].islower():
            valid = False
            break
    for i in range (5,9):
        if pan_no[i].isdigit():
            valid = False
            break
    if pan_no[9].isupper():
        valid = True
if valid == True:
    print("Valid PAN number")
else:
    print("Invalid PAN number")

Enter your PAN number ABCDE1234a


Invalid PAN number


In [ ]:
#Assignment 1
